# Generated by Django 6.1.1 on 2026-10-03 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('party_size', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='A pending hold lapses at this instant.', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tables.table')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['table', 'starts_at', 'ends_at'], name='reservation_table_i_4ab0fb_idx'), models.Index(fields=['status', 'starts_at'], name='reservation_status_130635_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reservation_ends_after_start'), models.CheckConstraint(condition=models.Q(('party_size__gt', 0)), name='reservation_party_size_positive')],
            },
        ),
    ]
