# Generated by Django 6.1.1 on 2026-10-05 08:44

import apps.invoices.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, storage=apps.invoices.storage.PrivateStorage(), upload_to='invoices/%Y/'),
        ),
    ]
