# Generated by Django 6.1.1 on 2026-10-03 07:39

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Restaurant', max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('opening_time', models.TimeField(default=datetime.time(9, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('slot_step_minutes', models.PositiveSmallIntegerField(default=30)),
                ('min_reservation_minutes', models.PositiveSmallIntegerField(default=30)),
                ('max_reservation_minutes', models.PositiveSmallIntegerField(default=180)),
                ('pending_reservation_expiry_minutes', models.PositiveSmallIntegerField(default=30)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'restaurant settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='settings_closing_after_opening'), models.CheckConstraint(condition=models.Q(('slot_step_minutes__gt', 0)), name='settings_slot_step_positive'), models.CheckConstraint(condition=models.Q(('min_reservation_minutes__gt', 0), ('min_reservation_minutes__lte', models.F('max_reservation_minutes'))), name='settings_reservation_bounds_valid'), models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='settings_tax_rate_percentage')],
            },
        ),
    ]
