# Generated by Django 6.1.1 on 2026-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='queue_minutes_per_party',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='restaurantsettings',
            constraint=models.CheckConstraint(condition=models.Q(('queue_minutes_per_party__gt', 0)), name='settings_queue_minutes_positive'),
        ),
    ]
