# Generated by Django 6.1.1 on 2026-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=10)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('qr_code', models.ImageField(blank=True, upload_to='tables/qr/')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='table_capacity_positive')],
            },
        ),
    ]
