# Generated by Django 6.1.1 on 2026-10-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='table',
            name='qr_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Raising it invalidates every QR code already printed for this table.'),
        ),
    ]
