# Generated by Django 6.1.1 on 2026-10-03 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9 ()-]{7,20}$')])),
                ('party_size', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('seated', 'Seated'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='waiting', max_length=10)),
                ('estimated_wait_time', models.PositiveSmallIntegerField(blank=True, help_text='Minutes, estimated when the ticket was issued.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Empty for walk-in guests registered by staff.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='queue_mgmt__status_a1da33_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('party_size__gt', 0)), name='queueticket_party_size_positive')],
            },
        ),
    ]
